# Changes here will be overwritten by Copier
AddAllcontributors: true
AddCodeOfConduct: false
AddContributionDocs: true
AddCopierCI: false
AddGitHubTemplates: true
AddMacToCI: true
AddPrecommit: true
AddWinToCI: false
AnswerStrategy: ask
AuthorEmail: nathan.allaire@polymtl.ca
AuthorName: Nathan Allaire
Indentation: 2
JuliaMinVersion: '1.9'
License: MPL-2.0
PackageName: ProxTV
PackageOwner: nathanemac
PackageUUID: 925ea013-038b-5ab6-a1ab-e0849925e528
RunJuliaNightlyOnCI: false
UseCirrusCI: false
_commit: v0.9.1
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
