exclude = [
  "@ref",
  "^https://github.com/.*/releases/tag/v.*$",
  "^https://doi.org/FIXME$",
  "^https://nathanemac.github.io/ProxTV.jl/stable$",
  "zenodo.org/badge/DOI/FIXME$",
  "^http://localhost",
  "localhost"
]

exclude_path = [
  "docs/build"
]
